### ISSUE TITLE
JAVA exception with Linux binary

### ISSUE THREAD

**Issue by BackSpace54** [vegardit/copycat#69]
Hello,

trying copycat binary on Manjaro, get JAVA exception at sync/watch command :
`./copycat-linux-amd64 sync ~/Documents/ ~/Temp/cc`
Exception in thread "main" java.awt.AWTError: Toolkit not found: sun.awt.X11.XToolkit
        at java.awt.Toolkit$2.run(Toolkit.java:595)
        at java.awt.Toolkit$2.run(Toolkit.java:583)
        at java.security.AccessController.doPrivileged(AccessController.java:87)
        at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:582)
        at java.awt.SystemTray.isSupported(SystemTray.java:221)
        at com.vegardit.copycat.util.DesktopNotifications.isSupported(DesktopNotifications.java:79)
        at com.vegardit.copycat.util.DesktopNotifications.<clinit>(DesktopNotifications.java:38)
        at com.vegardit.copycat.command.watch.WatchCommand.doExecute(WatchCommand.java:152)
        at com.vegardit.copycat.command.sync.AbstractSyncCommand.execute(AbstractSyncCommand.java:95)
        at com.vegardit.copycat.command.AbstractCommand.call(AbstractCommand.java:102)
        at com.vegardit.copycat.command.AbstractCommand.call(AbstractCommand.java:1)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:3461)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at com.vegardit.copycat.CopyCatMain.main(CopyCatMain.java:133)

FAT java version works
` java -jar ./copycat-fat.jar sync ~/Documents/ ~/Temp/cc`
15:08:59 [main] Effective Config:
copy-acl: false
delete: false
delete-excluded: false
dry-run: false
exclude-hidden-files: false
exclude-hidden-system-files: false
exclude-older-files: false
exclude-system-files: false
excludes: [
  ]
ignore-errors: false
ignore-symlink-errors: false
source: /home/flo/Documents
target: /home/flo/Temp/cc
threads: 2

**Comment by sebthom** [comment]
@BackSpace54 thanks for reporting. please try the latest build.

**Comment by BackSpace54** [comment]
With binary the config is empty:
`16:43:50 [main] WARN: Catched 
16:43:50 [main] Effective Config:
{
  }`

Same command with .jar show default config:
`16:44:54 [main] Effective Config:
copy-acl: false
delete: false
delete-excluded: false
dry-run: false
exclude-hidden-files: false
exclude-hidden-system-files: false
exclude-older-files: false
exclude-system-files: false
excludes: [
  ]
ignore-errors: false
ignore-symlink-errors: false
source: /home/flo/Documents
target: /home/flo/Temp/cc
threads: 2`

**Comment by BackSpace54** [comment]
Hi,
seems you're working hard on the snapshots ;-)
The config appears now with latest snapshot of the standalone version.
I let you work for now.
Very nice sync tool btw, waiting for first release.
Bye.
